### ISSUE TITLE
講義、回ごとの質問一覧取得

### ISSUE THREAD

**Issue by WhiteFox-Lugh** [ws-8/WS-8#19]
メニューから講義と回数を選択すると、
- 講義に出されている質問一覧
- 質問の表示
- その講義の概要
を表示してくれるようにする。また、質問詳細ページへのリンクをはる
さらに、質問がいっぱいある場合は、Pagenation を使って数ページに分ける（1ページあたり質問何件表示するかは実装してみて考える）

**Comment by Shin-kyoto** [comment]
get_questions#19ブランチを切って作業しています．
## できたこと

とりあえずできたことが，
- 講義に出されている質問一覧
- 質問の表示
- 講義の概要の表示

になっています．

## できていないこと
できていないことが，
- solvedかどうか，answerがあるかどうかで色を変更する
- 質問詳細ページへのリンク
- 質問がいっぱいある場合は、Pagenation を使って数ページに分ける

という状態です．

## 変更したコード
変更したコードの前後比較を（gitでできるにも関わらず）書いていきます．
### 1.`app/helpers/application_helper.rb`の変更
今回のcommitで一番大きい変更です．

- 前
```ruby
module ApplicationHelper
    def get_lectures
    # get courses and lessons
        @courses = Course.select("course_name")
        query = 'SELECT course_name, title FROM lessons, courses WHERE courses.id == lessons.course_id'
        @lessons = Course.find_by_sql(query)
    end
end
```

- 後
```ruby
module ApplicationHelper
    def get_lectures
    # get courses
        @courses=Course.all
    end
end
```
なぜこんな風にしたかというと，`lesson`の`id`を`params`で渡したかったためです．元のままだと，`@lessons`には,`course_name`と`title`のみが入っており，`id`が取得できていませんでした．
`@lesson`自体は，`view`で作成することにしています．（これがまずいかどうかは後述）

### 2.`app/views/layouts/application.html.erb`の変更
- 前
```ruby
<% @lessons.each do |l| %>
  <% if @course_name == l.course_name then %>
    <%= link_to l.title, question_list_path, class: "dropdown-item" %>
   <% end %>
<% end %>
```
- 後
```ruby
<% @lessons=Lesson.where(course_id:c.id) %>
<% @lessons.each do |l| %>
   <%= link_to l.title, question_list_path(id:l.id), class: "dropdown-item" %>
<% end %>
```
`app/helpers/application_helper.rb`の変更に伴いこちらも変更しています．`<% @lessons=Lesson.where(course_id:c.id) %>`の部分について，
- controllerで加工すべきじゃない？
- ヘルパーメソッドを使うべきじゃない？
という考えはよぎったのですが，一旦viewに書いてしまいました．やっぱりまずいかな・・・，

### 3. `config/routes.rb`の変更
これは自分が`question#index`を触らずに`question#ilist`を作ったため生じた変更です．
今思えば`question#index`をそのまま触っても良かったのですが，ブラウザで前後比較をするのに便利だったのでつい残してしまいました．ごめんなさい．
- 前
```ruby
get '/question_list', to: 'question#index'
```
- 後
```ruby
get '/question_list/:id', to: 'question#list', as: :question_list
```
### 4. `app/controllers/question_controller.rb`に`list`メソッド追加

```ruby
def list
    @lesson=Lesson.find(params[:id])
    @questions=Question.where(lesson_id:params[:id])
    @course=Course.find(@lesson.course_id)
end
```
### 5. `app/views/question/list.html.erb`の追加

```ruby
h2 class="text-lg-center"><%= @course.course_name %> <%= @lesson.title%></h2>
<% @teacher=User.find(@lesson.user_id) %>
<p class="text-lg-center" > 担当：<%= @teacher.name %> <%=@lesson.body%></p>

<% @questions.each do |q| %>
	<% @user=User.find(q.user_id) %>
	<div class="callout callout-warning card shadow-sm m-3">
		<div class="card-body">
			<h5 class="card-title mb-4 text-warning">
		  		<%= q.title%>
			<span class="badge badge-warning">回答受付中</span>
			</h5>
			<h6 class="card-subtitle mb-2 text-muted"><%=@user.name%></h6>
			<h6 class="card-subtitle mb-2 text-muted"><%=q.created_at%></h6>
			<p class="card-text">
				<%=q.body%>
			
			</p>
			<a href="#" class="card-link">詳しくみる</a>
		</div>
	</div>


<% end %>
```

`<% @teacher=User.find(@lesson.user_id) %>`とか，`<% @user=User.find(q.user_id) %>`とか，こんなの許されるんでしょうか？

## 困っていること
困っていることは，
- 質問の作成時刻がUTCで表示されてしまう
- コントローラからメソッドを呼び出すべき（かもしれない）ところを，viewに書いてしまっている
- 色分けの方法
- Pagenation 
という四点です．
ちょっと土日動けないんで，引き継いでもらえるとありがたいです．
issueのコメントはこういう風に使うべきじゃないよ，とか，プルリク出してないbranchからの変更点はこうすると簡単に引っ張ってこれるよ，とか，そういうのもすごく歓迎しています．よろしくお願いします．

**Comment by WhiteFox-Lugh** [comment]
上記の実装を引き継ぎました。

## 1. question.csv のテストデータを増やした

情報学展望2の質問の数を21にした。

## 2. タイムゾーンの変更

- /config/application.rb にタイムゾーンを東京にする指定を書いた
- /config/initializers/time_formats.rb にフォーマットを指定した

## 3. 質問の色分け

- `solved` が `TRUE` なら解決済みの色（success）で表示
- `solved` が `FALSE` なら回答受付中の色（warning）で表示

## 4. pagination の実装

- 質問が多い場合に pagination で10件ごとに区切って表示
- gemfile に kaminari を追加
- あとは /app/views/kaminari/ をみていただければなんとなくわかるかと
- 質問数を100以上にしてもうまく表示されることを確認（`rake db:seed` を複数回実行して重複して質問を投入した）

---

## 残り実装すること

- 質問詳細ページへのリンクを貼る
- 回答済み / 回答受付中のみ表示するみたいな機能があったほうがいいかも

**Comment by WhiteFox-Lugh** [comment]
merge した
