### ISSUE TITLE
新規質問投稿

### ISSUE THREAD

**Issue by WhiteFox-Lugh** [ws-8/WS-8#20]
講義、回を指定して、質問を投稿する機能を付ける

**Comment by nigiiro-taro** [comment]
ブランチ：post_question
にて、問題を投稿する機能を作成しました。ちゃんと動いていることも確認できていますが、どなたかお時間あればチェックをお願いします。大丈夫そうならpull request & mergeしておきます。

**Comment by nigiiro-taro** [comment]
## aaaa

**Comment by WhiteFox-Lugh** [comment]
軽く引継ぎ。

## 追加したこと

### 1. フォームの上に instruction を追加

新規質問投稿をします、的な文章、講義名と回数を表示。

### 2. conflict 解消

get_question#19 ブランチで質問一覧と質問詳細の view を少し変更したのでその変更を cherry-pick してきた。
これで merge するときに conflict しなくて済むはず。

### 3. エラー表示 / 投稿成功表示

↑の投稿失敗時のフラッシュをいい感じのエラー表示にした。
投稿成功時の表示もいい感じにした。

### 4. 投稿日時順にソート

質問リスト表示を新しい順にした

---

## 追加してほしい機能

- エラーが発生した時にフォームが空欄になってしまわないようにする
- 投稿のプレビュー機能

**Comment by nigiiro-taro** [comment]
### 追加した機能
エラーが発生した時にフォームが空欄になってしまわないようにするように変更しました。
また、lessonとcourseをlistやcreateで同じものを使っているため、一つにまとめてbefore_actionで読み込むようにしました。

### コメント
投稿のプレビュー機能はrequiredではなく、optionalな気がしたため一旦issueにあげて、ここでpost_question機能の開発はストップしてdevelopにmergeします。（動くのを確認しています。）
多分、優先順位はanserフォームとかの方が高いので、そちらをやろうと思っています。

**Comment by WhiteFox-Lugh** [comment]
動作チェックして develop へ merge したのでこの issue は close します。
