### ISSUE TITLE
新規回答、コメント投稿

### ISSUE THREAD

**Issue by WhiteFox-Lugh** [ws-8/WS-8#21]
質問に対しての回答とコメントの投稿機能を付ける

**Comment by Shin-kyoto** [comment]
# @answer.save がうまくいかない #21
`post_questions`ブランチに，回答の投稿機能を実装していますが，`@answer.save` がうまくいかず（`if @answer.save`が通らない），回答が保存できていない状況です．

## 1. viewの変更
- `app/views/post_answer/new.html.erb `に以下の内容を記述し，回答を紐付けたい質問内容を表示できるようにしました

```ruby
<h2 class="text-lg-center">
	<%= @course.course_name %> <%= @lesson.title%>
</h2>
<div class="callout callout-primary card shadow-sm m-3">
	<div class="card-body">
		<h5 class="card-title mb-4">
			<%= @question.title %>
		</h5>
		<h6 class="card-subtitle mb-2 text-muted">
			<i class="fas fa-user"></i>
			<%= if (@user.nickname).blank? then @user.name else @user.nickname end %>
		</h6>
		<h6 class="card-subtitle mb-2 text-muted">
			<%= @question.created_at.to_s(:datetime_jp)%>
		</h6>
		<p class="card-text">
			<%= @question.body %>
		</p>
	</div>
</div>
```
問題なく動作しています．

- 新規回答を投稿できるようにしようとした

rootingは通ります．しかし，`@answer`が`save`できていないようです.(エラーについては3. で後述)

```ruby
<div class="callout callout-info card shadow-sm m-3">

	<%= form_with model: @answer, url: create_answer_path, local: true do |a| %>
	<h5 class="text-info">回答内容</h5>
	<%= a.text_area :body, class:"form-control mb-2", rows:"15", placeholder:"回答内容を入力してください"%>
	<%= a.hidden_field :question_id , :value => params[:id]%>
	<%= a.hidden_field :user_id , :value => current_user.id%>
	<%= a.submit "投稿する", class:"btn btn-info btn-block w-25", :required => true%>
	<% end %>
</div>
```



## 2. routes の変更
- `config/routes.rb`に以下の内容を記述し，`create_answer_path`を使って`app/controllers/post_answer_controller.rb`の`create`メソッドを呼び出しました
```
  get '/post_answer/:id', to: 'post_answer#new', as: :post_answer
  post '/post_answer/:id' , to: 'post_answer#create', as: :create_answer
```

## 3. controller の変更
`@answer.save`して，質問の詳細（`question_detail_path`）へ飛ぼうとしましたが，` if @answer.save`が通らず，elseの方へ飛ばされてしまいます．
どうやらモデルがsaveできていないようですが，何がいけないのかつかめていないです．

```ruby
class PostAnswerController < ApplicationController
  def new
    @question = Question.find(params[:id])
    @user = User.find(@question.user_id)
    @lesson = Lesson.find(@question.lesson_id)
    @course = Course.find(@lesson.course_id)
  end

  def create
    @answer = Answer.new
    # binding.pry
    if @answer.save
      redirect_to question_detail_path, notice: 'Posted Successfully!'
    else
      flash[:alert] = @answer.errors
      redirect_to question_list_path
    end
  end


  private

  def answer_params
    params.require(:answer).permit(:body, :user_id, :question_id)
  end
end
```


モデルがsaveできない（`@answer.save`がうまくいかない）ので困っています．問題が起こっている場所が掴めていない状態です．

**Comment by Shin-kyoto** [comment]
# 回答できるようになってます
回答関連でできていないこと
- Scoreを増やせない
Scoreを増やすボタンが実装されていないです．

Questionの，Me tooも実装されていないです
post_answersブランチはひとまず動くので，ここでブランチ切って，続きはpost_commentsブランチで作業します

# 回答成功した時と失敗した時の動作
- 成功した時
質問詳細画面に遷移します．回答が増えていることがわかると思います．
- 失敗した時
回答投稿画面に戻されます．

**Comment by Shin-kyoto** [comment]
# コメントできるようになってます
コメント関連でできていないこと
- Scoreを増やせない
Scoreを増やすボタンが実装されていないです．


# コメント成功した時と失敗した時の動作
- 成功した時
質問詳細画面に遷移します．コメントが増えていることがわかると思います．
- 失敗した時
コメント投稿画面に戻されます．

# ボタン
ボタンの色がなぜか灰色なので，直し方知ってたら教えてください

**Comment by WhiteFox-Lugh** [comment]
ありがとうございます！！動作確認しました。

新規質問投稿の view, controller のスクリプトにならって、回答内容 / コメント内容が空欄だった時にエラー表示するようにすると、なおいいかなって思います！

> ボタンの色がなぜか灰色なので，直し方知ってたら教えてください
どこでしょう？ちなみにカラー指定は avantui の `primary`, `secondary`, `danger`, `warning`, `success`, `info` のプリセットのカラーしか使ってません。

> Scoreを増やすボタンが実装されていないです．
スコアの文字の色は意図的に `warning` の橙色を使ったので、ボタンを実装する際は橙色に指定してくれるととても嬉しいです。

それに伴って、ボタンの色についてですが、
1. 「回答する！」ボタンを `primary` の青色、「コメントする」を `info` の水色にする
2. 「回答する！」ボタンも「コメントする」ボタンもどちらも `info` の水色にする
のどちらかにした方がいい気がします。なんとなく1を推していますが。

**Comment by Shin-kyoto** [comment]
コメントありがとうございます！
# エラー表示
questionを参考に，エラー表示できるようにしました．
回答内容 / コメント内容が空欄だった時に以下のエラー表示が出ます
```
 Error!
   body
      can't be blank
```

# ボタンの色
http://localhost:3000/question_detail/3
こちらのページにアクセスすると，ボタンがグレーで表示されています．実装としては，
```
<%= link_to '回答する！', post_answer_path(id:@question.id),type: 'button', class: 'btn btn-info btn-block w-25 mt-4' %>
```
としています．ちなみに，`class: 'btn btn-info btn-block w-25 mt-4'`を，`class: 'btn btn-primary btn-block w-25 mt-4'`と変えても，色はグレーのままです
