### ISSUE TITLE
回答の承認（Authorize）/ 解決済み、未解決の切り替え

### ISSUE THREAD

**Issue by WhiteFox-Lugh** [ws-8/WS-8#23]
先生が回答を正解、承認とする機能の追加

**Comment by WhiteFox-Lugh** [comment]
Issue #19 ができないと作業ができない！ので後回しです

**Comment by Shin-kyoto** [comment]
# authorizedブランチ
- Authorized,unauthorized,Solved,Unsolvedを実装しました
- metoo,scoreを実装しました
しかし残念な見た目になっているので，AvantUIのアイコンをボタンとする方法を探しています
