### ISSUE TITLE
投稿のプレビュー機能

### ISSUE THREAD

**Issue by nigiiro-taro** [ws-8/WS-8#31]

**Comment by WhiteFox-Lugh** [comment]
## できたこと

markdown で表示できるようになった

## 今後

プレビュー機能をどうする？

リアルタイムで入力内容を反映する？
https://azarashi-blogs.com/2019-02-22-011403/#%E3%83%AA%E3%82%A2%E3%83%AB%E3%82%BF%E3%82%A4%E3%83%A0%E3%83%97%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC%E3%81%AE%E5%AE%9F%E8%A3%85

それとも、プレビューボタンを押すと render される（もしくは jQuery を用いて反映する）ようにする？

**Comment by WhiteFox-Lugh** [comment]
### 新規投稿のリアルタイムプレビュー

新規質問投稿だけリアルタイムプレビューができた
ソースコードの syntax highlight ができないけどまあいい感じ

### syntax highlight

投稿した後はソースコードの syntax highlight が見えるようになる
ちなみにハイライトのテーマは GitHub のスタイルと同じ
